# Using the httpYac plugin for VS Code
# code --install-extension anweber.vscode-httpyac

@http-url = http://localhost:5711

GET {{http-url}}/hello

#?? status == 200

###
GET {{http-url}}/hello/John%20Smith

#?? status == 200

###
POST {{http-url}}/echo
Accept: application/json
Custom: New-Header

{
    "custom-body": "Body content",
    "title": "value"
}

#?? status == 200

###
GET {{http-url}}/Secure

#?? status == 403

###
GET {{http-url}}/FakeToken

{{
  $global.token=response.body;
}}

?? status == 200

###
GET {{http-url}}/echo
bearer: {{ $global.token }}

?? status == 200

### Secure with hard coded token
GET {{http-url}}/Secure
bearer: "fakeToken123xyz"

?? status == 200

